name: volvox
favicon: null
layout_spectrum: 0.16887
typography_spectrum: 0.73716
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#697eab'
    - '#3f4d6f'
    - '#96edfd'
  brandStrength: 0.1875
  lightness: 0.6788392846938223
  saturation: 0.375
  rhythmicContrast: 0.5748455082066357
purpose: []
